// Compact birthplace dataset: country -> list of major cities.
// Not exhaustive (a full world gazetteer is 150k+ rows); this covers common
// countries + their largest cities for a clean dropdown + type-ahead. The city
// field also accepts free text, so anything missing can still be typed.
module.exports = {
  "United States": ["New York","Los Angeles","Chicago","Houston","Phoenix","Philadelphia","San Antonio","San Diego","Dallas","Miami","West Palm Beach","Orlando","Tampa","Jacksonville","Atlanta","Boston","Seattle","Denver","Washington DC","Las Vegas","Detroit","Nashville","Charlotte","San Francisco","Austin"],
  "Canada": ["Toronto","Montreal","Vancouver","Calgary","Ottawa","Edmonton","Winnipeg","Quebec City","Halifax"],
  "United Kingdom": ["London","Birmingham","Manchester","Glasgow","Liverpool","Leeds","Edinburgh","Bristol","Cardiff","Belfast"],
  "Ireland": ["Dublin","Cork","Galway","Limerick"],
  "Australia": ["Sydney","Melbourne","Brisbane","Perth","Adelaide","Gold Coast","Canberra"],
  "New Zealand": ["Auckland","Wellington","Christchurch"],
  "Mexico": ["Mexico City","Guadalajara","Monterrey","Cancun","Tijuana","Puebla"],
  "Brazil": ["Sao Paulo","Rio de Janeiro","Brasilia","Salvador","Fortaleza","Belo Horizonte"],
  "Argentina": ["Buenos Aires","Cordoba","Rosario","Mendoza"],
  "Colombia": ["Bogota","Medellin","Cali","Barranquilla","Cartagena"],
  "Spain": ["Madrid","Barcelona","Valencia","Seville","Bilbao","Malaga"],
  "France": ["Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Bordeaux"],
  "Germany": ["Berlin","Munich","Hamburg","Frankfurt","Cologne","Stuttgart","Dusseldorf"],
  "Italy": ["Rome","Milan","Naples","Turin","Florence","Venice","Bologna"],
  "Portugal": ["Lisbon","Porto","Faro"],
  "Netherlands": ["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven"],
  "Belgium": ["Brussels","Antwerp","Ghent","Bruges"],
  "Switzerland": ["Zurich","Geneva","Basel","Bern","Lausanne"],
  "Sweden": ["Stockholm","Gothenburg","Malmo"],
  "Norway": ["Oslo","Bergen","Trondheim"],
  "Denmark": ["Copenhagen","Aarhus","Odense"],
  "Poland": ["Warsaw","Krakow","Lodz","Wroclaw","Gdansk"],
  "Greece": ["Athens","Thessaloniki","Patras","Heraklion"],
  "Russia": ["Moscow","Saint Petersburg","Novosibirsk","Yekaterinburg"],
  "Ukraine": ["Kyiv","Kharkiv","Odesa","Lviv","Dnipro"],
  "Turkey": ["Istanbul","Ankara","Izmir","Antalya","Bursa"],
  "India": ["Mumbai","Delhi","Bangalore","Hyderabad","Chennai","Kolkata","Pune","Ahmedabad","Jaipur"],
  "Pakistan": ["Karachi","Lahore","Islamabad","Faisalabad","Rawalpindi"],
  "Bangladesh": ["Dhaka","Chittagong","Khulna"],
  "China": ["Beijing","Shanghai","Guangzhou","Shenzhen","Chengdu","Wuhan","Hong Kong"],
  "Japan": ["Tokyo","Osaka","Yokohama","Nagoya","Sapporo","Kyoto","Fukuoka"],
  "South Korea": ["Seoul","Busan","Incheon","Daegu"],
  "Philippines": ["Manila","Quezon City","Cebu","Davao"],
  "Indonesia": ["Jakarta","Surabaya","Bandung","Medan","Bali (Denpasar)"],
  "Thailand": ["Bangkok","Chiang Mai","Phuket","Pattaya"],
  "Vietnam": ["Ho Chi Minh City","Hanoi","Da Nang"],
  "Malaysia": ["Kuala Lumpur","George Town","Johor Bahru"],
  "Singapore": ["Singapore"],
  "United Arab Emirates": ["Dubai","Abu Dhabi","Sharjah"],
  "Saudi Arabia": ["Riyadh","Jeddah","Mecca","Medina","Dammam"],
  "Israel": ["Jerusalem","Tel Aviv","Haifa"],
  "Egypt": ["Cairo","Alexandria","Giza"],
  "Nigeria": ["Lagos","Abuja","Kano","Ibadan"],
  "Kenya": ["Nairobi","Mombasa","Kisumu"],
  "South Africa": ["Johannesburg","Cape Town","Durban","Pretoria"],
  "Ghana": ["Accra","Kumasi"],
  "Morocco": ["Casablanca","Rabat","Marrakesh","Fez"],
  "Jamaica": ["Kingston","Montego Bay"],
  "Dominican Republic": ["Santo Domingo","Santiago","Punta Cana"],
  "Puerto Rico": ["San Juan","Ponce","Bayamon"],
  "Cuba": ["Havana","Santiago de Cuba"],
  "Chile": ["Santiago","Valparaiso","Concepcion"],
  "Peru": ["Lima","Arequipa","Cusco"],
  "Venezuela": ["Caracas","Maracaibo","Valencia"],
  "Other": ["(type your city)"]
};
